### ISSUE TITLE
Heatmap failed to render in Logseq 0.7.1

### ISSUE THREAD

**Issue by kumo** [pengx17/logseq-plugin-heatmap#266]
I updated this plugin, but now it no longer works. In the UI, it says "Heatmap failed to render..." and in the developer log, it gives the error `TypeError: Hm[t] is not a function`, in particular:

```
index.4316e42a.js:41 TypeError: Hm[t] is not a function
    at index.4316e42a.js:41
    at index.4316e42a.js:41
    at index.4316e42a.js:41
    at Object.i [as prefetch] (index.4316e42a.js:41)
    at Bm (index.4316e42a.js:41)
    at index.4316e42a.js:49
```

**Comment by pengx17** [comment]
What is your language setting for Logseq?
________________________________
发件人: Robert Clarke ***@***.***>
发送时间: Tuesday, June 7, 2022 7:24:12 PM
收件人: pengx17/logseq-plugin-heatmap ***@***.***>
抄送: Subscribed ***@***.***>
主题: [pengx17/logseq-plugin-heatmap] Heatmap failed to render in Logseq 0.7.1 (Issue #266)


I updated this plugin, but now it no longer works. In the UI, it says "Heatmap failed to render..." and in the developer log, it gives the error TypeError: Hm[t] is not a function, in particular:

index.4316e42a.js:41 TypeError: Hm[t] is not a function
    at index.4316e42a.js:41
    at index.4316e42a.js:41
    at index.4316e42a.js:41
    at Object.i [as prefetch] (index.4316e42a.js:41)
    at Bm (index.4316e42a.js:41)
    at index.4316e42a.js:49


―

**Comment by antomal** [comment]
I have this problem too.
In the settings, the Russian language.

**Comment by antomal** [comment]
No, sorry! I have a problem in version 0.7.2.
Everything worked fine in 0.7.1.

**Comment by kumo** [comment]
> What is your language setting for Logseq?

English

**Comment by pengx17** [comment]
I have pushed a new version. Could you please see if that version would fix your issue or not? @kumo

**Comment by antomal** [comment]
My problem remains.
Moreover, there is no problem on the second laptop, but on this one it appeared today after updating to 0.7.2. I don't know how to see the log :-(

**Comment by pengx17** [comment]
I have reverted https://github.com/pengx17/logseq-plugin-heatmap/commit/da8ed62a57c6232043882af51df65208dff92d92. Not sure if it will fix for you 🤔

**Comment by antomal** [comment]
Updated. Works!

**Comment by kumo** [comment]
> I have pushed a new version. Could you please see if that version would fix your issue or not? @kumo

Yes, this works for me too thanks. I had upgraded to 0.7.2 and the problem was the same,  but with this latest update to the plugin, it works again.
